const SET_PEOPLE = "SET_PEOPLE";
const SET_PLANETS = "SET_PLANETS";
const LOAD_MORE = "LOAD_MORE";
const IS_LOADED = "IS_LOADED";
const GET_MORE_PEOPLE = "GET_MORE_PEOPLE";
const GET_MORE_PLANETS = "GET_MORE_PLANETS";
const IS_LOADED_PLANETS = "IS_LOADED_PLANETS";
const SET_STARSHIPS_TO_STORE = "SET_STARSHIPS_TO_STORE";
const GET_MORE_STARSHIPS = "GET_MORE_STARSHIPS";
const IS_LOADED_STARSHIPS = "IS_LOADED_STARSHIPS";

export {
	IS_LOADED_STARSHIPS,
	GET_MORE_STARSHIPS,
	SET_STARSHIPS_TO_STORE,
	IS_LOADED_PLANETS,
	GET_MORE_PEOPLE,
	GET_MORE_PLANETS,
	SET_PEOPLE,
	SET_PLANETS,
	LOAD_MORE,
	IS_LOADED,
};
