const SET_PEOPLE_TO_STORE = "SET_PEOPLE_TO_STORE";
const SET_PLANETS_TO_STORE = "SET_PLANETS_TO_STORE";
const SET_STARSHIPS_TO_STORE = "SET_STARSHIPS_TO_STORE";
const SET_FILMS_TO_STORE = "SET_FILMS_TO_STORE";

const GET_MORE_PEOPLE = "GET_MORE_PEOPLE";
const GET_MORE_PLANETS = "GET_MORE_PLANETS";
const GET_MORE_STARSHIPS = "GET_MORE_STARSHIPS";

const IS_LOADED_PEOPLE = "IS_LOADED_PEOPLE";
const IS_LOADED_PLANETS = "IS_LOADED_PLANETS";
const IS_LOADED_STARSHIPS = "IS_LOADED_STARSHIPS";

export {
	SET_FILMS_TO_STORE,
	SET_PEOPLE_TO_STORE,
	SET_PLANETS_TO_STORE,
	SET_STARSHIPS_TO_STORE,
	GET_MORE_STARSHIPS,
	GET_MORE_PEOPLE,
	GET_MORE_PLANETS,
	IS_LOADED_STARSHIPS,
	IS_LOADED_PLANETS,
	IS_LOADED_PEOPLE,
};
